name: 'nasa_photos'
description: 'A new Flutter project. Created by Snowman Labs with Flutter Snow Blower'

# The following line prevents the package from being accidentally published to
 # pub.dev using `pub publish`. This is preferred for private packages.

# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# We inserted the following format, for versioning control:

# <<YEAR>>.<<MILESTONE>>.<<FIXES>>.

# YEAR: represents the year of product launch, receiving the AAAA format.
# MILESTONE: represents the project milestone, being non-negative integers.
# FIXES: represents the bug fixes, being non-negative integers.

# All products will be launched with this version format, following the example: 2020.1.1
# To more info please visit our Handbook at https://handbook.snowmanlabs.com/desenvolvimento/qa/controle-de-versao.html
version: 2020.1.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'


dependencies:
  google_fonts: ^1.1.1
  flutter_snow_base: ^0.1.5+1
  flutter_modular: ^2.0.1
  lazy_load_refresh_indicator: ^1.0.0+1
  simple_search_bar: ^0.1.7
  shimmer: ^1.1.1
  cached_network_image: ^2.2.0+1
  intl: ^0.16.1
  flutter_mobx: ^1.1.0+1
  mobx: ^1.2.1+1
  dio: ^3.0.9
  i18n_extension: ^1.4.1
  flutter:
    sdk: flutter


dev_dependencies:
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0+1
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


# The following section is specific to Flutter.
flutter:

# The following line ensures that the Material Icons font is
# included with your application, so that you can use the icons in
# the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages